### PR TITLE
Enable moving of figures from inside figure editor

### PR DESCRIPTION
**Pull request by ptwz**
When creating a sequence, sometimes you need to shuffle around figures within a sequence.
This can sometimes become somewhat tricky, my changes bring new buttons to the figure editor, which enable moving the selected figure within the sequence.

### CODE REVIEW

**Comment by OpenAero** [comment]
Thank you. I will be looking at this next week.

**Comment by OpenAero** [comment]
I tested the update. Unfortunately it does not work well with figures that are preceded by a move, comment, figure letter etc. Try figure string;
"@A" -4,3m,6;f (-5,12) "@B" frdb24

Also, I'm not sure about adding the buttons to the figure editor. There are already many buttons there. Maybe adding them to the figure drawing in the sequence would be better. For example bottom left and right.

**Comment by ptwz** [comment]
Ok, didn't test this. Intentionally movements where not moved around. Now comments stay in place, too.

Regarding the buttons, I wasn't shure that having e.g. move arrows on the figure in the drawing could negatively affect touch interfaces... What do you think?

**Comment by OpenAero** [comment]
It will be necessary to take the touch interface into account, but it can be done. Would be similar to the magnifying glass in top right of figure.

**Pull request merged**
